/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhujohnle_androidreplay_ndk_Test */

#ifndef _Included_com_zhujohnle_androidreplay_ndk_Test
#define _Included_com_zhujohnle_androidreplay_ndk_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhujohnle_androidreplay_ndk_Test
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhujohnle_androidreplay_ndk_Test_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
